language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable


before_script:
  - cargo install cargo-travis --force
  - export PATH=$HOME/.cargo/bin:$PATH;

script:
  - cargo build
  - cargo test

after_success:
  - cargo coveralls


dist: trusty
#sudo: false

